In [1]:
import numpy as np

In [2]:
## Create arrayas using numpy
## Create a 1d array

arr1 = np.array([1,2,3,4,5])

print(arr1)

[1 2 3 4 5]


In [3]:
print(type(arr1))

<class 'numpy.ndarray'>


In [4]:
print(arr1.shape)

(5,)


In [5]:
#1D Array
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) ##One rwo and five columns

array([[1, 2, 3, 4, 5]])

In [6]:
## 2D array

arr3=np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr3)
print(arr3.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [7]:
np.arange(0,10,3).reshape(4,1)

array([[0],
       [3],
       [6],
       [9]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
## Identity matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
##Attributes of Numpy Array

arr = np.array([[1,2,3], [4,5,6]])

print("Array:\n", arr)
print("Shape:", arr.shape) # Shape of the array
print("Number of the dimensions:", arr.ndim) # dimensions
print("Size (Number of elements):", arr.size)
print("Data Type:", arr.dtype)
print("Item size(in bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of the dimensions: 2
Size (Number of elements): 6
Data Type: int64
Item size(in bytes): 8


In [11]:
## Numpy vectorized Operation

arry1 = np.array([1,2,3,4,5])
arry2 = np.array([10,20,30,40,50])

# Addtions

print("Addtions:", arry1 + arry2)

# Substraction

print("Substraction:", arry1 - arry2)

#Multiplication

print("Multiplcation:", arry1*arry2)

#Dividided

print("Divided:", arry2/arry1)

Addtions: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplcation: [ 10  40  90 160 250]
Divided: [10. 10. 10. 10. 10.]


In [12]:
## Array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("Array:\n", arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
arr[1][2:]

array([7, 8])

In [14]:
arr[0:, 2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [15]:
arr[2:,3]

array([12])

In [16]:
print(arr[1:, 1:3])

[[ 6  7]
 [10 11]]


In [17]:
# Modify the elements

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
arr[1][2] =49 
print(arr)

[[ 1  2  3  4]
 [ 5  6 49  8]
 [ 9 10 11 12]]


In [19]:
arr[2][1:] = 100
print(arr)

[[  1   2   3   4]
 [  5   6  49   8]
 [  9 100 100 100]]


In [20]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

print("Mean:", np.mean(data))
print("Median:",np.median(data))
print("Standerd Deviation:", np.std(data))
print("Variance:", np.var(data))

Mean: 5.5
Median: 5.5
Standerd Deviation: 2.8722813232690143
Variance: 8.25


In [21]:
## Logical Operation
data = np.array([1,2,3,4,5,6,7,8,9,10])
data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [22]:
data[data>5]

array([ 6,  7,  8,  9, 10])

In [23]:
data[(data>=5) & (data<=9)]


array([5, 6, 7, 8, 9])