In [1]:
import numpy as np

In [4]:
## Create arrayas using numpy
## Create a 1d array

arr1 = np.array([1,2,3,4,5])

print(arr1)

[1 2 3 4 5]


In [5]:
print(type(arr1))

<class 'numpy.ndarray'>


In [6]:
print(arr1.shape)

(5,)


In [11]:
#1D Array
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) ##One rwo and five columns

array([[1, 2, 3, 4, 5]])

In [17]:
## 2D array

arr3=np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr3)
print(arr3.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [22]:
np.arange(0,10,3).reshape(4,1)

array([[0],
       [3],
       [6],
       [9]])

In [24]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
## Identity matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
##Attributes of Numpy Array

arr = np.array([[1,2,3], [4,5,6]])

print("Array:\n", arr)
print("Shape:", arr.shape) # Shape of the array
print("Number of the dimensions:", arr.ndim) # dimensions
print("Size (Number of elements):", arr.size)
print("Data Type:", arr.dtype)
print("Item size(in bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of the dimensions: 2
Size (Number of elements): 6
Data Type: int64
Item size(in bytes): 8


In [27]:
## Numpy vectorized Operation

arry1 = np.array([1,2,3,4,5])
arry2 = np.array([10,20,30,40,50])

# Addtions

print("Addtions:", arry1 + arry2)

# Substraction

print("Substraction:", arry1 - arry2)

#Multiplication

print("Multiplcation:", arry1*arry2)

#Dividided

print("Divided:", arry2/arry1)

Addtions: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplcation: [ 10  40  90 160 250]
Divided: [10. 10. 10. 10. 10.]


In [28]:
## Array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("Array:\n", arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
arr[1][2:]

array([7, 8])

In [31]:
arr[0:, 2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [32]:
arr[2:,3]

array([12])

In [35]:
print(arr[1:, 1:3])

[[ 6  7]
 [10 11]]


In [37]:
# Modify the elements

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [38]:
arr[1][2] =49 
print(arr)

[[ 1  2  3  4]
 [ 5  6 49  8]
 [ 9 10 11 12]]


In [39]:
arr[2][1:] = 100
print(arr)

[[  1   2   3   4]
 [  5   6  49   8]
 [  9 100 100 100]]


In [40]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

print("Mean:", np.mean(data))
print("Median:",np.median(data))
print("Standerd Deviation:", np.std(data))
print("Variance:", np.var(data))

Mean: 5.5
Median: 5.5
Standerd Deviation: 2.8722813232690143
Variance: 8.25


In [43]:
## Logical Operation
data = np.array([1,2,3,4,5,6,7,8,9,10])
data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [44]:
data[data>5]

array([ 6,  7,  8,  9, 10])

In [49]:
data[(data>=5) & (data<=9)]


array([5, 6, 7, 8, 9])

In [1]:
import numpy as np

In [4]:
## Create arrays with using numpy

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [8]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1, 5)

array([[1, 2, 3, 4, 5]])

In [11]:
arr3 = np.array([[1,2,3,4,5]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]]
(1, 5)


In [12]:
arr3 = np.array([[1,2,3,4,5], [2,3,4,5,6]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [16]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [17]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [20]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
## Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print('Array Shape:', arr.shape)
print("Number of the dimensions: ", arr.ndim)
print("Size (numbers of the elements):", arr.size)
print("Data Type:", arr.dtype)
print("Item Size (in bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Array Shape: (2, 3)
Number of the dimensions:  2
Size (numbers of the elements): 6
Data Type: int64
Item Size (in bytes): 8


In [24]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print(f"Addtion: {arr1 + arr2}")
print(f"Substraction: {arr1-arr2}")
print(f"Multiplication: {arr1*arr2}")
print(f"Division: {arr1/arr2}")

Addtion: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [30]:
#Universal Functions
print("Square root:", np.sqrt(arr1))
print("Cube Root:", np.cbrt(arr1))
print("Exponetial:", np.exp(arr1))
print("Sine:", np.sin(arr1))
print("Natural log:", np.log(arr1))

Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Cube Root: [1.         1.25992105 1.44224957 1.58740105 1.70997595]
Exponetial: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Natural log: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [31]:
# Slicing

arr = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
print("Array \n:", arr)

Array 
: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
print(arr[0][0])

1


In [34]:
print(arr[2][2])

11


In [38]:
print(arr[1:, 2:])

[[ 7  8]
 [11 12]]


In [39]:
print(arr[1:3,1:3])

[[ 6  7]
 [10 11]]


In [40]:
arr[1,2]=49
print(arr)

[[ 1  2  3  4]
 [ 5  6 49  8]
 [ 9 10 11 12]]


In [41]:
arr[1:] =100
print(arr)

[[  1   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [42]:
#Sum of an Array:
print(arr)

[[  1   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [43]:
sum_of_array = arr.sum()
print(sum_of_array)

810


In [44]:
#Array Reshaping:

One_D = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(One_D.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [45]:
One_D.max()

np.int64(12)

In [46]:
array1 = np.array(range(1, 11))
print(array1)

[ 1  2  3  4  5  6  7  8  9 10]


In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.size)

(2, 3)
6


In [50]:
#Indexing and slicing:

arr = np.array([10, 20, 30, 40, 50, 60])

print(arr[0:3])
print(arr[4:])



[10 20 30]
[50 60]


In [54]:
print(arr.min())
print(arr.max())

10
60


In [55]:
#Array Transpose: Given a 2D NumPy array, write a function to transpose it.

def transpose_array(arr):
    return np.transpose(arr)


In [57]:
Matrix = np.array([[1,2,3],[4,5,6]])
Transpose_array = transpose_array(Matrix)

print("Original array: \n", Matrix)
print("Transpose array: \n", Transpose_array)

Original array: 
 [[1 2 3]
 [4 5 6]]
Transpose array: 
 [[1 4]
 [2 5]
 [3 6]]


In [58]:
import pandas as pd

In [64]:
data = [1,2,3,4,5]

series = pd.Series(data)

print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>


In [62]:
df = pd.DataFrame([[1,2,3,4,5],["Vimal", "Varun", "Haseena", "Luna", "Laskshmi"]])
print(df)
print(type(df))

       0      1        2     3         4
0      1      2        3     4         5
1  Vimal  Varun  Haseena  Luna  Laskshmi
<class 'pandas.core.frame.DataFrame'>


In [65]:
#Create a series from dictionary

data = {"a": 1, "b":2, "c": 3, "d":4}

df1 = pd.Series(data)

print(df1)
print(type(df1))

a    1
b    2
c    3
d    4
dtype: int64
<class 'pandas.core.series.Series'>


In [69]:
data = [10,20,30]
index = ["a", 'b', 'c']

pd.Series(data, index=index)

a    10
b    20
c    30
dtype: int64

In [70]:
df = pd.read_csv("data.csv")
print(df)

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-0

In [73]:
data = {
    "Name":["Vimal", "Haseena", "Kamal"],
    "Age":[25,26,27],
    "City":["Chennai", "Madurai", "Thrichy"]
}

print(data)

{'Name': ['Vimal', 'Haseena', 'Kamal'], 'Age': [25, 26, 27], 'City': ['Chennai', 'Madurai', 'Thrichy']}


In [74]:
df = pd.DataFrame(data)
print(df)

      Name  Age     City
0    Vimal   25  Chennai
1  Haseena   26  Madurai
2    Kamal   27  Thrichy


In [2]:
import pandas as pd

In [28]:
data = [

    {"Name":"Vimal", "Age": 25, "City": "Chennai"},
    {"Name": "Haseena", "Age": 25, "City": "USA"}
]

df = pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age     City
0    Vimal   25  Chennai
1  Haseena   25      USA
<class 'pandas.core.frame.DataFrame'>


In [29]:
df["Name"]

0      Vimal
1    Haseena
Name: Name, dtype: object

In [30]:
df[["Name", "Age", "City"]]

Name  Age     City
0    Vimal   25  Chennai
1  Haseena   25      USA

In [31]:
df.loc[0]

Name      Vimal
Age          25
City    Chennai
Name: 0, dtype: object

In [32]:
df.loc[1]

Name    Haseena
Age          25
City        USA
Name: 1, dtype: object

In [33]:
df.iloc[0]

Name      Vimal
Age          25
City    Chennai
Name: 0, dtype: object

In [34]:
df.iloc[0][2]

C:\Users\vimal\AppData\Local\Temp\ipykernel_19824\2519637664.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][2]


'Chennai'

In [35]:
##Acessing spefice elements:

df.at[1, "Age"]

np.int64(25)

In [36]:
df["Salary"] = [60000,50000]

In [37]:
df

Name  Age     City  Salary
0    Vimal   25  Chennai   60000
1  Haseena   25      USA   50000

In [38]:
df.drop("Salary", axis=1, inplace=True)
df

Name  Age     City
0    Vimal   25  Chennai
1  Haseena   25      USA

In [39]:
df["Age"] = df["Age"]+1
df

Name  Age     City
0    Vimal   26  Chennai
1  Haseena   26      USA

In [40]:
df = pd.read_csv("data.csv")
df

Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    NaN  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    NaN  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    NaN   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    NaN   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    NaN  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [41]:
df.head()

Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [42]:
df.tail()

Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [43]:
df.describe()

Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [44]:
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [45]:
df.info

<bound method DataFrame.info of           Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   93.0  P

In [50]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [47]:
df.isna().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [51]:
df.isnull().any()

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [52]:
df.isna().any()

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [53]:
## Filling the missing values with mean

df["Value_fillna"] = df["Value"].fillna(df["Value"].mean())
df

Date Category  Value   Product  Sales Region  Value_fillna
0   2023-01-01        A   28.0  Product1  754.0   East     28.000000
1   2023-01-02        B   39.0  Product3  110.0  North     39.000000
2   2023-01-03        C   32.0  Product2  398.0   East     32.000000
3   2023-01-04        B    8.0  Product1  522.0   East      8.000000
4   2023-01-05        B   26.0  Product3  869.0  North     26.000000
5   2023-01-06        B   54.0  Product3  192.0   West     54.000000
6   2023-01-07        A   16.0  Product1  936.0   East     16.000000
7   2023-01-08        C   89.0  Product1  488.0   West     89.000000
8   2023-01-09        C   37.0  Product3  772.0   West     37.000000
9   2023-01-10        A   22.0  Product2  834.0   West     22.000000
10  2023-01-11        B    7.0  Product1  842.0  North      7.000000
11  2023-01-12        B   60.0  Product2    NaN   West     60.000000
12  2023-01-13        A   70.0  Product3  628.0  South     70.000000
13  2023-01-14        A   69.0  Product1  423.0   East     69.000000
14  2023-01-15        A   47.0  Product2  893.0   West     47.000000
15  2023-01-16        C    NaN  Product1  895.0  North     51.744681
16  2023-01-17        C   93.0  Product2  511.0  South     93.000000
17  2023-01-18        C    NaN  Product1  108.0   West     51.744681
18  2023-01-19        A   31.0  Product2  578.0   West     31.000000
19  2023-01-20        A   59.0  Product1  736.0   East     59.000000
20  2023-01-21        C   82.0  Product3  606.0  South     82.000000
21  2023-01-22        C   37.0  Product2  992.0  South     37.000000
22  2023-01-23        B   62.0  Product3  942.0  North     62.000000
23  2023-01-24        C   92.0  Product2  342.0   West     92.000000
24  2023-01-25        A   24.0  Product2  458.0   East     24.000000
25  2023-01-26        C   95.0  Product1  584.0   West     95.000000
26  2023-01-27        C   71.0  Product2  619.0  North     71.000000
27  2023-01-28        C   56.0  Product2  224.0  North     56.000000
28  2023-01-29        B    NaN  Product3  617.0  North     51.744681
29  2023-01-30        C   51.0  Product2  737.0  South     51.000000
30  2023-01-31        B   50.0  Product3  735.0   West     50.000000
31  2023-02-01        A   17.0  Product2  189.0   West     17.000000
32  2023-02-02        B   63.0  Product3  338.0  South     63.000000
33  2023-02-03        C   27.0  Product3    NaN   East     27.000000
34  2023-02-04        C   70.0  Product3  669.0   West     70.000000
35  2023-02-05        B   60.0  Product2    NaN   West     60.000000
36  2023-02-06        C   36.0  Product3  177.0   East     36.000000
37  2023-02-07        C    2.0  Product1    NaN  North      2.000000
38  2023-02-08        C   94.0  Product1  408.0  South     94.000000
39  2023-02-09        A   62.0  Product1  155.0   West     62.000000
40  2023-02-10        B   15.0  Product1  578.0   East     15.000000
41  2023-02-11        C   97.0  Product1  256.0   East     97.000000
42  2023-02-12        A   93.0  Product3  164.0   West     93.000000
43  2023-02-13        A   43.0  Product3  949.0   East     43.000000
44  2023-02-14        A   96.0  Product3  830.0   East     96.000000
45  2023-02-15        B   99.0  Product2  599.0   West     99.000000
46  2023-02-16        B    6.0  Product1  938.0  South      6.000000
47  2023-02-17        B   69.0  Product3  143.0   West     69.000000
48  2023-02-18        C   65.0  Product3  182.0  North     65.000000
49  2023-02-19        C   11.0  Product3  708.0  North     11.000000

In [54]:
## Filling the missing values with median

df["Sales_fillna"] = df["Sales"].fillna(df["Sales"].median())
df

Date Category  Value   Product  Sales Region  Value_fillna  \
0   2023-01-01        A   28.0  Product1  754.0   East     28.000000   
1   2023-01-02        B   39.0  Product3  110.0  North     39.000000   
2   2023-01-03        C   32.0  Product2  398.0   East     32.000000   
3   2023-01-04        B    8.0  Product1  522.0   East      8.000000   
4   2023-01-05        B   26.0  Product3  869.0  North     26.000000   
5   2023-01-06        B   54.0  Product3  192.0   West     54.000000   
6   2023-01-07        A   16.0  Product1  936.0   East     16.000000   
7   2023-01-08        C   89.0  Product1  488.0   West     89.000000   
8   2023-01-09        C   37.0  Product3  772.0   West     37.000000   
9   2023-01-10        A   22.0  Product2  834.0   West     22.000000   
10  2023-01-11        B    7.0  Product1  842.0  North      7.000000   
11  2023-01-12        B   60.0  Product2    NaN   West     60.000000   
12  2023-01-13        A   70.0  Product3  628.0  South     70.000000   
13  2023-01-14        A   69.0  Product1  423.0   East     69.000000   
14  2023-01-15        A   47.0  Product2  893.0   West     47.000000   
15  2023-01-16        C    NaN  Product1  895.0  North     51.744681   
16  2023-01-17        C   93.0  Product2  511.0  South     93.000000   
17  2023-01-18        C    NaN  Product1  108.0   West     51.744681   
18  2023-01-19        A   31.0  Product2  578.0   West     31.000000   
19  2023-01-20        A   59.0  Product1  736.0   East     59.000000   
20  2023-01-21        C   82.0  Product3  606.0  South     82.000000   
21  2023-01-22        C   37.0  Product2  992.0  South     37.000000   
22  2023-01-23        B   62.0  Product3  942.0  North     62.000000   
23  2023-01-24        C   92.0  Product2  342.0   West     92.000000   
24  2023-01-25        A   24.0  Product2  458.0   East     24.000000   
25  2023-01-26        C   95.0  Product1  584.0   West     95.000000   
26  2023-01-27        C   71.0  Product2  619.0  North     71.000000   
27  2023-01-28        C   56.0  Product2  224.0  North     56.000000   
28  2023-01-29        B    NaN  Product3  617.0  North     51.744681   
29  2023-01-30        C   51.0  Product2  737.0  South     51.000000   
30  2023-01-31        B   50.0  Product3  735.0   West     50.000000   
31  2023-02-01        A   17.0  Product2  189.0   West     17.000000   
32  2023-02-02        B   63.0  Product3  338.0  South     63.000000   
33  2023-02-03        C   27.0  Product3    NaN   East     27.000000   
34  2023-02-04        C   70.0  Product3  669.0   West     70.000000   
35  2023-02-05        B   60.0  Product2    NaN   West     60.000000   
36  2023-02-06        C   36.0  Product3  177.0   East     36.000000   
37  2023-02-07        C    2.0  Product1    NaN  North      2.000000   
38  2023-02-08        C   94.0  Product1  408.0  South     94.000000   
39  2023-02-09        A   62.0  Product1  155.0   West     62.000000   
40  2023-02-10        B   15.0  Product1  578.0   East     15.000000   
41  2023-02-11        C   97.0  Product1  256.0   East     97.000000   
42  2023-02-12        A   93.0  Product3  164.0   West     93.000000   
43  2023-02-13        A   43.0  Product3  949.0   East     43.000000   
44  2023-02-14        A   96.0  Product3  830.0   East     96.000000   
45  2023-02-15        B   99.0  Product2  599.0   West     99.000000   
46  2023-02-16        B    6.0  Product1  938.0  South      6.000000   
47  2023-02-17        B   69.0  Product3  143.0   West     69.000000   
48  2023-02-18        C   65.0  Product3  182.0  North     65.000000   
49  2023-02-19        C   11.0  Product3  708.0  North     11.000000   

    Sales_fillna  
0          754.0  
1          110.0  
2          398.0  
3          522.0  
4          869.0  
5          192.0  
6          936.0  
7          488.0  
8          772.0  
9          834.0  
10         842.0  
11         591.5  
12         628.0  
13         423.0  
14         893.0  
15         895.0  
16         511

In [55]:
df.isna().sum()

Date            0
Category        0
Value           3
Product         0
Sales           4
Region          0
Value_fillna    0
Sales_fillna    0
dtype: int64

In [56]:
##Rename the columns

df = df.rename(columns={"Date": "Sales_date"})
print(df)

    Sales_date Category  Value   Product  Sales Region  Value_fillna  \
0   2023-01-01        A   28.0  Product1  754.0   East     28.000000   
1   2023-01-02        B   39.0  Product3  110.0  North     39.000000   
2   2023-01-03        C   32.0  Product2  398.0   East     32.000000   
3   2023-01-04        B    8.0  Product1  522.0   East      8.000000   
4   2023-01-05        B   26.0  Product3  869.0  North     26.000000   
5   2023-01-06        B   54.0  Product3  192.0   West     54.000000   
6   2023-01-07        A   16.0  Product1  936.0   East     16.000000   
7   2023-01-08        C   89.0  Product1  488.0   West     89.000000   
8   2023-01-09        C   37.0  Product3  772.0   West     37.000000   
9   2023-01-10        A   22.0  Product2  834.0   West     22.000000   
10  2023-01-11        B    7.0  Product1  842.0  North      7.000000   
11  2023-01-12        B   60.0  Product2    NaN   West     60.000000   
12  2023-01-13        A   70.0  Product3  628.0  South     70.00

In [57]:
##Change datatype

df["Value_fillna"] = df["Value_fillna"].astype(int)
df.head()

Sales_date Category  Value   Product  Sales Region  Value_fillna  \
0  2023-01-01        A   28.0  Product1  754.0   East            28   
1  2023-01-02        B   39.0  Product3  110.0  North            39   
2  2023-01-03        C   32.0  Product2  398.0   East            32   
3  2023-01-04        B    8.0  Product1  522.0   East             8   
4  2023-01-05        B   26.0  Product3  869.0  North            26   

   Sales_fillna  
0         754.0  
1         110.0  
2         398.0  
3         522.0  
4         869.0

In [58]:
df["Sales_fillna"] = df["Sales_fillna"].astype(int)
df.head()

Sales_date Category  Value   Product  Sales Region  Value_fillna  \
0  2023-01-01        A   28.0  Product1  754.0   East            28   
1  2023-01-02        B   39.0  Product3  110.0  North            39   
2  2023-01-03        C   32.0  Product2  398.0   East            32   
3  2023-01-04        B    8.0  Product1  522.0   East             8   
4  2023-01-05        B   26.0  Product3  869.0  North            26   

   Sales_fillna  
0           754  
1           110  
2           398  
3           522  
4           869

In [59]:
df.drop(columns="Sales", axis=1, inplace=True)

In [61]:
df.drop(columns="Value", axis=1, inplace=True)

In [62]:
df.head()

Sales_date Category   Product Region  Value_fillna  Sales_fillna
0  2023-01-01        A  Product1   East            28           754
1  2023-01-02        B  Product3  North            39           110
2  2023-01-03        C  Product2   East            32           398
3  2023-01-04        B  Product1   East             8           522
4  2023-01-05        B  Product3  North            26           869