# Module: NumPy Assignments
## Lesson: NumPy




### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [33]:
### Assignment 1: Array Creation and Manipulation

# Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
# Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

import numpy as np

In [34]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(arr1)
print(arr1.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
(5, 5)


In [35]:
arr1[:,2] = 1

In [36]:
print(arr1)

[[ 1  2  1  4  5]
 [ 6  7  1  9 10]
 [11 12  1 14 15]
 [16 17  1 19 20]
 [21 22  1 24 25]]


In [37]:
arr = np.random.randint(1, 21, size=(5,5))
print(arr.shape)
print("Original arr:\n", arr)

arr[:,2]=1
print(arr.shape)
print("Moddifed arr:\n", arr)

(5, 5)
Original arr:
 [[ 8  5  7 13 17]
 [ 9 13  9 13  1]
 [14  2  7  9  4]
 [18  6 19 17  2]
 [ 8 13  7  3 11]]
(5, 5)
Moddifed arr:
 [[ 8  5  1 13 17]
 [ 9 13  1 13  1]
 [14  2  1  9  4]
 [18  6  1 17  2]
 [ 8 13  1  3 11]]


In [38]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

arr2 = np.random.randint(1, 16, size=(4,4))
print(arr2.shape)
print("Orginal_array:\n", arr2)

np.fill_diagonal(arr2, 0)
print("Modified_array:\n", arr2)

(4, 4)
Orginal_array:
 [[ 6  9  3  1]
 [10 11 12 12]
 [13  2  5 15]
 [ 8  3  5 15]]
Modified_array:
 [[ 0  9  3  1]
 [10  0 12 12]
 [13  2  0 15]
 [ 8  3  5  0]]


In [39]:
### Assignment 2: Array Indexing and Slicing

#1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
#2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [40]:
arr10 = np.random.randint(1, 36, size=(6,6))
print(arr.shape)
print(arr)

(5, 5)
[[ 8  5  1 13 17]
 [ 9 13  1 13  1]
 [14  2  1  9  4]
 [18  6  1 17  2]
 [ 8 13  1  3 11]]


In [41]:
arr10[2:5,1:4]

array([[12, 18, 16],
       [ 9, 12, 10],
       [ 9, 25,  7]], dtype=int32)

In [42]:
num = np.random.randint(1, 20, size = (5,5))
print(num.shape)
print(num)



modified_num = np.concatenate((num[0, :], num[-1, :], num[1:-1, 0], num[1:-1, -1]))
print(modified_num)

(5, 5)
[[ 1 10  8  2 10]
 [13  9 17 10  5]
 [13  6 18 18 12]
 [13 17 10 13 15]
 [12  5  3 13 10]]
[ 1 10  8  2 10 12  5  3 13 10 13 13 13  5 12 15]


In [43]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(arr1)
print(arr1.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
(5, 5)


In [44]:
modified_arr1 = np.concatenate((arr1[0,:], arr1[-1,:], arr[1:-1,0],arr[-1:-1,1]))
print(modified_arr1)

[ 1  2  3  4  5 21 22 23 24 25  9 14 18]
