# Module: NumPy Assignments
## Lesson: NumPy













### Assignment 9: Structured Arrays


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [2]:
### Assignment 1: Array Creation and Manipulation

# Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
# Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

import numpy as np

In [3]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(arr1)
print(arr1.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
(5, 5)


In [4]:
arr1[:,2] = 1

In [5]:
print(arr1)

[[ 1  2  1  4  5]
 [ 6  7  1  9 10]
 [11 12  1 14 15]
 [16 17  1 19 20]
 [21 22  1 24 25]]


In [6]:
arr = np.random.randint(1, 21, size=(5,5))
print(arr.shape)
print("Original arr:\n", arr)

arr[:,2]=1
print(arr.shape)
print("Moddifed arr:\n", arr)

(5, 5)
Original arr:
 [[11 16 15  9 10]
 [11  1  6  2  1]
 [ 2  2  4  8  7]
 [11  5 17 10 12]
 [ 1 17 17  2 10]]
(5, 5)
Moddifed arr:
 [[11 16  1  9 10]
 [11  1  1  2  1]
 [ 2  2  1  8  7]
 [11  5  1 10 12]
 [ 1 17  1  2 10]]


In [7]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

arr2 = np.random.randint(1, 16, size=(4,4))
print(arr2.shape)
print("Orginal_array:\n", arr2)

np.fill_diagonal(arr2, 0)
print("Modified_array:\n", arr2)

(4, 4)
Orginal_array:
 [[ 8 11  3  9]
 [ 3  7 14  2]
 [ 9  2  6 13]
 [14 14  7 15]]
Modified_array:
 [[ 0 11  3  9]
 [ 3  0 14  2]
 [ 9  2  0 13]
 [14 14  7  0]]


In [8]:
### Assignment 2: Array Indexing and Slicing

#1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
#2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [9]:
arr10 = np.random.randint(1, 36, size=(6,6))
print(arr.shape)
print(arr)

(5, 5)
[[11 16  1  9 10]
 [11  1  1  2  1]
 [ 2  2  1  8  7]
 [11  5  1 10 12]
 [ 1 17  1  2 10]]


In [10]:
arr10[2:5,1:4]

array([[10,  2,  7],
       [35, 15,  2],
       [ 8, 33, 26]], dtype=int32)

In [11]:
num = np.random.randint(1, 20, size = (5,5))
print(num.shape)
print(num)



modified_num = np.concatenate((num[0, :], num[-1, :], num[1:-1, 0], num[1:-1, -1]))
print(modified_num)

(5, 5)
[[ 6 10 12 13 19]
 [ 2  4  5 17  2]
 [ 2  5  2 18  1]
 [18 19 16 10  5]
 [ 1 11  8 16 16]]
[ 6 10 12 13 19  1 11  8 16 16  2  2 18  2  1  5]


In [12]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(arr1)
print(arr1.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
(5, 5)


In [13]:
modified_arr1 = np.concatenate((arr1[0,:], arr1[-1,:], arr[1:-1,0],arr[-1:-1,1]))
print(modified_arr1)

[ 1  2  3  4  5 21 22 23 24 25 11  2 11]


In [ ]:
### Assignment 3: Array Operations

#1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.


In [17]:
num1 = np.random.randint(1, 15, size =(3, 4))
num2 = np.random.randint(1, 15, size =(3, 4))

print("Original num1 array:\n", num1)
print("Original num2 array:\n", num2)


#Addition:
print("Additions:\n", num1+num2)

#subtraction:
print("Subtraction:\n", num1-num2)

#Multiplication:
print("Multiplication:\n", num1*num2)

#Division:
print("Division:\n", num1/num2)

Original num1 array:
 [[12  8  6  7]
 [ 7  8  2  3]
 [ 1  5 11  6]]
Original num2 array:
 [[14  4 13  7]
 [13 14  1 13]
 [ 4 10 11 12]]
Additions:
 [[26 12 19 14]
 [20 22  3 16]
 [ 5 15 22 18]]
Subtraction:
 [[ -2   4  -7   0]
 [ -6  -6   1 -10]
 [ -3  -5   0  -6]]
Multiplication:
 [[168  32  78  49]
 [ 91 112   2  39]
 [  4  50 121  72]]
Division:
 [[0.85714286 2.         0.46153846 1.        ]
 [0.53846154 0.57142857 2.         0.23076923]
 [0.25       0.5        1.         0.5       ]]


In [18]:
#2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

array1 = np.random.randint(1, 16, size = (4, 4))
print(array1)
print(array1.shape)

[[12  2 15  8]
 [ 8  2 15  5]
 [11 14 12 11]
 [ 4  6 14  8]]
(4, 4)


In [20]:
rwo_wise_sum1 = array1[0].sum()
rwo_wise_sum2 = array1[1].sum()
rwo_wise_sum3 = array1[2].sum()
rwo_wise_sum4 = array1[3].sum()

print("First rwo_wise_sum:\n", rwo_wise_sum1)
print("Second rwo wise sum:\n", rwo_wise_sum2)
print("Third row wise sum:\n", rwo_wise_sum3)
print("Fourth row wise sum:\n", rwo_wise_sum4)

First rwo_wise_sum:
 37
Second rwo wise sum:
 30
Third row wise sum:
 48
Fourth row wise sum:
 32


In [29]:
array1

array([[12,  2, 15,  8],
       [ 8,  2, 15,  5],
       [11, 14, 12, 11],
       [ 4,  6, 14,  8]], dtype=int32)

In [43]:
print(array1[:-1])

[[12  2 15  8]
 [ 8  2 15  5]
 [11 14 12 11]]


In [46]:
number = np.arange(1, 17).reshape(4, 4)
print("Orginal array:\n", number)
print(number.shape)

#Compute the row-wise and column-wise sum.

row_wise_sum = np.sum(number, axis=1)
columns_wise_sum = np.sum(number, axis=0)

print(f"row_wise_sum: {row_wise_sum}")
print(f"columns_wise_sum: {columns_wise_sum}")

Orginal array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)
row_wise_sum: [10 26 42 58]
columns_wise_sum: [28 32 36 40]


In [ ]:

### Assignment 4: Statistical Operations

#1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.


In [49]:
numpy_array = np.random.randint(1, 20, size = (5,5))
print(f"Orginal numpy array: {numpy_array}")
print(f"Shape of the numpy array: {numpy_array.shape}")

#mean:
print(f"Mean of the numpy array: {np.mean(numpy_array)}")

#median:
print(f"Median of the numpy array: {np.median(numpy_array)}")

#standard deviation:
print(f"Standard deviation of the numpy array: {np.std(numpy_array)}")

#variance:
print(f"variance of the numpy array:{np.var(numpy_array)}")

Orginal numpy array: [[11 16  1 16  7]
 [ 5  3  3 10 18]
 [ 2 15 18 11 16]
 [15  6  9 17  7]
 [ 7  7 16 18 10]]
Shape of the numpy array: (5, 5)
Mean of the numpy array: 10.56
Median of the numpy array: 10.0
Standard deviation of the numpy array: 5.477809781290329
variance of the numpy array:30.0064


In [ ]:
#2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [52]:
numpy = np.arange(1,10).reshape(3,3)
print(numpy)
print(numpy.shape)

mean_array = np.mean(numpy)
std_array = np.std(numpy)

print(f"Orginal array of the mean is: {mean_array}")
print(f"Orginal std of the array is: {std_array}")

normalization = (numpy - mean_array)/std_array

print(f"Normalaization of the array: {normalization}")

print(f"Mean of the normalaization of the array is: {np.mean(normalization)}")
print(f"Std of the normalization of the array is:{np.std(normalization)}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
Orginal array of the mean is: 5.0
Orginal std of the array is: 2.581988897471611
Normalaization of the array: [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
Mean of the normalaization of the array is: 0.0
Std of the normalization of the array is:1.0


In [ ]:

### Assignment 5: Broadcasting


In [ ]:
#1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [57]:
numpy1 = np.random.randint(1, 10, size=(3,3))
row_wise = np.random.randint(1, 10, size=(3,))
print("Orginal array")
print(numpy1)
print("Row_wise_array")
print(row_wise)

#Add a 1D array

add = numpy1 + row_wise
print("Add a 1D array of shape(3,):\n", add)


Orginal array
[[1 4 2]
 [4 8 3]
 [5 1 8]]
Row_wise_array
[3 1 6]
Add a 1D array of shape(3,):
 [[ 4  5  8]
 [ 7  9  9]
 [ 8  2 14]]


In [ ]:
#2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [ ]:
array = np.random.randint(1, 20, size = (4,4))
columns_wise = np.random.randint(1, 20, size=(4,))
print("Orginal array")
print(array)
print("Columns_wise")
print(columns_wise)

#substract

result = array - columns_wise[:]
print("Result of the array")
print(result)

Orginal array
[[16 16  4  5]
 [12 11  4  2]
 [ 6  4  3  1]
 [16  4  2 10]]
Columns_wise
[ 6  5  6 13]
Result of the array
[[ 10  11  -2  -8]
 [  6   6  -2 -11]
 [  0  -1  -3 -12]
 [ 10  -1  -4  -3]]


In [59]:
array = np.random.randint(1, 20, size = (4,4))
columns_wise = np.random.randint(1, 20, size=(4,))
print("Orginal array")
print(array)
print("Columns_wise")
print(columns_wise)

#substract

result = array - columns_wise[:, np.newaxis]
print("Result of the array")
print(result)

Orginal array
[[11 13  7 10]
 [ 8 14 16  9]
 [17 13  4 10]
 [ 9  8 16  3]]
Columns_wise
[ 6 14  4 19]
Result of the array
[[  5   7   1   4]
 [ -6   0   2  -5]
 [ 13   9   0   6]
 [-10 -11  -3 -16]]


In [ ]:
### Assignment 6: Linear Algebra

#1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.


In [60]:
matrix = np.random.randint(1, 10, size = (3,3))
print("Matrix")
print(matrix)

determiant = np.linalg.det(matrix)
print(f"Determiant: {determiant}")

inverse = np.linalg.inv(matrix)
print(f"Inverser:{inverse}")

eigenvalues = np.linalg.eig(matrix)
print(f"Eigenvalues: {eigenvalues}")

Matrix
[[6 8 1]
 [4 6 3]
 [5 4 1]]
Determiant: 37.99999999999998
Inverser:[[-0.15789474 -0.10526316  0.47368421]
 [ 0.28947368  0.02631579 -0.36842105]
 [-0.36842105  0.42105263  0.10526316]]
Eigenvalues: EigResult(eigenvalues=array([13.2903764+0.j        , -0.1451882+1.68467567j,
       -0.1451882-1.68467567j]), eigenvectors=array([[ 0.68351082+0.j        , -0.02632824-0.56856212j,
        -0.02632824+0.56856212j],
       [ 0.56513212+0.j        ,  0.22291002+0.43119584j,
         0.22291002-0.43119584j],
       [ 0.4619942 +0.j        , -0.6636454 +0.j        ,
        -0.6636454 -0.j        ]]))


In [64]:
#2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

numpy1 = np.random.randint(1, 10, size=(2,3))
numpy2 = np.random.randint(1, 10, size =(3, 2))
print("array1")
print(numpy1)
print("array2")
print(numpy2)

matrix = np.dot(numpy1,numpy2)
print("Matrix multiplication:\n", matrix)

array1
[[7 4 9]
 [3 7 9]]
array2
[[5 7]
 [9 9]
 [8 6]]
Matrix multiplication:
 [[143 139]
 [150 138]]


In [ ]:
### Assignment 7: Advanced Array Manipulation

#1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).


In [65]:
numpy_array = np.arange(1, 10).reshape(3, 3)
print("Orginal shape of array")
print(numpy_array)

reshape_array1 = numpy_array.reshape(1, 9)
print("Reshape of the array to (1, 9)")
print(reshape_array1)

reshape_array2 = reshape_array1.reshape(9, 1)
print("Again the reshape of the array to back is (9, 1)")
print(reshape_array2)

Orginal shape of array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshape of the array to (1, 9)
[[1 2 3 4 5 6 7 8 9]]
Again the reshape of the array to back is (9, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [67]:
#2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

numpy = np.random.randint(1, 20, size=(5, 5))
print("Shape")
print(numpy.shape)
print("Orginal array")
print(numpy)

flattern = numpy.flatten()
print("Flattern numpy array")
print(flattern)
print(flattern.shape)

reshape = flattern.reshape(5 , 5)
print("Reshape the flattern numpy array into (5, 5)")
print(reshape)

Shape
(5, 5)
Orginal array
[[ 6 17  6 12 18]
 [ 5 14  1 10  9]
 [10 19 14 11  6]
 [ 9 14  1 12 18]
 [11 18  9 10 15]]
Flattern numpy array
[ 6 17  6 12 18  5 14  1 10  9 10 19 14 11  6  9 14  1 12 18 11 18  9 10
 15]
(25,)
Reshape the flattern numpy array into (5, 5)
[[ 6 17  6 12 18]
 [ 5 14  1 10  9]
 [10 19 14 11  6]
 [ 9 14  1 12 18]
 [11 18  9 10 15]]


In [ ]:
### Assignment 8: Fancy Indexing and Boolean Indexing

#1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.


In [85]:
numpy = np.random.randint(1, 21, size = (5, 5))
print(numpy)

#Extract the elements at the corners of the array:

corrner = numpy[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corroner of the elements")
print(corrner)



[[11 10 10 15  7]
 [12  9 16  8  6]
 [ 4 16  5  5 12]
 [16 12  9  6 10]
 [12  6  9  2 18]]
Corroner of the elements
[11  7 12 18]


In [86]:
numpy[0,0]

np.int32(11)

In [88]:
numpy[-1,-1]

np.int32(18)

In [81]:
numpy[4,0]

np.int32(4)

In [82]:
numpy[4,4]

np.int32(5)

In [90]:
#2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

numpy = np.random.randint(1, 20, size = (4, 4))
print(numpy.shape)
print(numpy)

numpy[numpy>10]=10
print("modified array")
print(numpy)

(4, 4)
[[ 4  9  1  7]
 [12  7 18 19]
 [ 1 19 10 14]
 [ 8 14  1 15]]
modified array
[[ 4  9  1  7]
 [10  7 10 10]
 [ 1 10 10 10]
 [ 8 10  1 10]]


In [ ]:
#1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [93]:
data_type = [("name", "U10"),("age", "i4"),("weight", "f4")]

data = np.array([("Vimal",25,65.8),("Dhayalan",26,70.5),("Manikandan",28,70.90), ("Haseena", 25, 65.20)], dtype= data_type)
print("Orginal data")
print(data)

sorted_by_age = np.sort(data,order="age")
print("Sorted by age")
print(sorted_by_age)


Orginal data
[('Vimal', 25, 65.8) ('Dhayalan', 26, 70.5) ('Manikandan', 28, 70.9)
 ('Haseena', 25, 65.2)]
Sorted by age
[('Haseena', 25, 65.2) ('Vimal', 25, 65.8) ('Dhayalan', 26, 70.5)
 ('Manikandan', 28, 70.9)]
